from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle, Paragraph
from reportlab.platypus.doctemplate import SimpleDocTemplate
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
import os

def export_pdf(report_data, client_name="Client"):
    from datetime import datetime

    if not os.path.exists("reports"):
        os.makedirs("reports")

    safe_client_name = client_name.replace(" ", "_")
    output_path = f"reports/{safe_client_name}_Compliance_Report.pdf"

    # Setup canvas
    c = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER
    margin = 50
    y = height - margin
    page_count = 1

    # Set metadata
    c.setAuthor("ComplyAI")
    c.setTitle(f"{client_name} - Compliance Report")
    c.setSubject("Compliance Assessment Report")
    c.setKeywords("Compliance, Cybersecurity, Report, Audit")

    # === COVER PAGE ===
    logo_path = "assets/logo.png"
    if os.path.exists(logo_path):
        c.drawImage(logo_path, margin, y - 60, width=55, height=55, preserveAspectRatio=True, mask="auto")

    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(colors.HexColor("#003366"))
    c.drawString(margin + 75, y - 30, "Compliance Assessment Report")

    c.setFont("Helvetica", 12)
    c.setFillColor(colors.black)
    c.drawString(margin, y - 100, f"Client: {client_name}")
    c.drawString(margin, y - 115, f"Generated On: {report_data['executive_summary']['report_generated_at']}")

    # Footer + page number
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    c.drawString(margin, 30, "© 2025 ComplyAI Inc. | Confidential Document")
    c.drawRightString(width - margin, 30, f"Page {page_count}")
    page_count += 1

    c.showPage()

    # === EXECUTIVE SUMMARY ===
    def add_page_number(canvas_obj, page_num):
        c.setFont("Helvetica-Bold", 16)
        c.setFillColor(colors.HexColor("#003366"))
        c.drawString(margin, height - margin, "Executive Summary")

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    y = height - margin - 30
    for key, value in report_data["executive_summary"].items():
        if key == "report_generated_at":
            continue
        c.drawString(margin, y, f"{key}: {value}")
        y -= 15

    # === CONTROL COVERAGE REPORT TITLE ===
    y -= 30
    if y < 150:
        # Footer + page number
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(colors.grey)
        c.drawString(margin, 30, "Generated by ComplyAI | Confidential Report")
        c.drawRightString(width - margin, 30, f"Page {page_count}")
        page_count += 1
        c.showPage()
        y = height - margin

    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(colors.HexColor("#003366"))
    c.drawString(margin, y, "Control Coverage Report")
    y -= 20

    # === TABLE SETUP ===
    styles = getSampleStyleSheet()
    data = [["Sentence", "Status", "Framework", "Closest Control", "Suggested Improvement"]]
    for item in report_data["detailed_report"]:
        row = [
            Paragraph(item.get("Policy Sentence", "N/A")[:300], styles["Normal"]),
            Paragraph(item.get("Status", "N/A"), styles["Normal"]),
            Paragraph(item.get("Framework", "N/A"), styles["Normal"]),
            Paragraph(item.get("Closest Control", "N/A")[:300], styles["Normal"]),
            Paragraph(item.get("Suggested Improvement", "N/A")[:300], styles["Normal"]),
        ]
        data.append(row)

    table = Table(
        data,
        colWidths=[
            2.0 * inch,  # Policy Sentence
            0.8 * inch,  # Status
            1.0 * inch,  # Framework
            1.8 * inch, # Closest Control
            2.0 * inch, # Suggested Improvement
        ],
        repeatRows=1
    )

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#003366")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.whitesmoke),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 9),
        ("FONTSIZE", (0, 1), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.lightgrey]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))

    table_width, table_height = table.wrap(0, 0)
    table_x = (width - table_width) / 2
    table.wrapOn(c, width, height)
    table.drawOn(c, table_x, y - table_height)

    # Footer + page number
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    c.drawString(margin, 30, "Generated by ComplyAI | Confidential Report")
    c.drawRightString(width - margin, 30, f"Page {page_count}")

    c.save()
    return os.path.abspath(output_path)
