# scripts/pdf_exporter.py
# This script will generate a PDF report of the compliance assessment results using the ReportLab library. It will include an executive summary and a detailed control coverage report.

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle, Image
import os

def export_compliance_report_to_pdf(report_data, client_name="Client"):
    safe_client_name = client_name.replace(" ", "_")  # sanitize filename
    output_path = f"reports/{safe_client_name}_Compliance_Report.pdf"

    # Make sure reports/ directory exists
    if not os.path.exists("reports"):
        os.makedirs("reports")

    c = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER

    # ==== HEADER ====
    # Draw logo (Optional)
    logo_path = "assets/logo.png"
    if os.path.exists(logo_path):
        c.drawImage(logo_path, 50, height - 80, width=100, preserveAspectRatio=True, mask='auto')

    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.darkblue)
    c.drawString(200, height - 50, "Compliance Assessment Report")

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    c.drawString(50, height - 100, f"Client: {client_name}")
    c.drawString(50, height - 115, f"Generated On: {report_data['executive_summary']['report_generated_at']}")

    # ==== Executive Summary ====
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.darkblue)
    c.drawString(50, height - 140, "Executive Summary")

    y = height - 160
    for key, value in report_data["executive_summary"].items():
        c.setFont("Helvetica", 10)
        c.setFillColor(colors.black)
        c.drawString(50, y, f"{key}: {value}")
        y -= 15

    # ==== Detailed Findings ====
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.darkblue)
    c.drawString(50, y - 20, "Control Coverage Report")

    data = [["Sentence", "Status", "Framework", "Closest Control", "Suggested Improvement"]]
    for item in report_data["detailed_report"]:
        data.append([
            item["Policy Sentence"][:30] + "...",
            item["Status"],
            item["Framework"],
            item["Closest Control"][:30] + "...",
            item.get("Suggested Improvement", "N/A")[:30] + "..."
        ])

    table = Table(data, colWidths=[100, 60, 60, 130, 130])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#003366")),  # Header color
        ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),
        ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,0), 9),
        ("FONTSIZE", (0,1), (-1,-1), 7),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.whitesmoke, colors.lightgrey]),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
    ]))

    y = y - 50
    table.wrapOn(c, width, height)
    table.drawOn(c, 50, y - len(data) * 15)

    # ==== Footer ====
    c.setFont("Helvetica", 8)
    c.setFillColor(colors.grey)
    c.drawString(50, 30, "Generated by ComplyAI - Confidential")

    c.save()
    return os.path.abspath(output_path)