# scripts/pdf_exporter.py

from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import Table, TableStyle
from reportlab.lib.units import inch
import os

def export_compliance_report_to_pdf(report_data, client_name="Client"):
    # Output Path
    if not os.path.exists("reports"):
        os.makedirs("reports")

    safe_client_name = client_name.replace(" ", "_")
    output_path = f"reports/{safe_client_name}_Compliance_Report.pdf"

    # Setup canvas
    c = canvas.Canvas(output_path, pagesize=LETTER)
    width, height = LETTER
    margin = 50

    # --- Header ---
    logo_path = "assets/logo.png"
    if os.path.exists(logo_path):
        c.drawImage(logo_path, margin, height - 80, width=80, preserveAspectRatio=True, mask='auto')

    c.setFont("Helvetica-Bold", 18)
    c.setFillColor(colors.darkblue)
    c.drawString(margin + 100, height - 60, "Compliance Assessment Report")

    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    c.drawString(margin, height - 100, f"Client: {client_name}")
    c.drawString(margin, height - 115, f"Generated On: {report_data['executive_summary']['report_generated_at']}")

    # --- Executive Summary ---
    y = height - 140
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.darkblue)
    c.drawString(margin, y, "Executive Summary")

    y -= 20
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.black)
    for key, value in report_data["executive_summary"].items():
        c.drawString(margin, y, f"{key}: {value}")
        y -= 15

    # --- Control Coverage Report ---
    y -= 20
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(colors.darkblue)
    c.drawString(margin, y, "Control Coverage Report")

    # Table Headers + Rows
    data = [["Sentence", "Status", "Framework", "Closest Control", "Suggested Improvement"]]
    for item in report_data["detailed_report"]:
        data.append([
            item["Policy Sentence"][:50] + "...",
            item["Status"],
            item["Framework"],
            item["Closest Control"][:50] + "...",
            item.get("Suggested Improvement", "N/A")[:50] + "..."
        ])

    table = Table(data, colWidths=[2.0*inch, 0.8*inch, 0.9*inch, 2.0*inch, 2.0*inch])
    table.setStyle(TableStyle([
        ("BACKGROUND", (0,0), (-1,0), colors.HexColor("#003366")),
        ("TEXTCOLOR", (0,0), (-1,0), colors.whitesmoke),
        ("ALIGN", (0,0), (-1,-1), "LEFT"),
        ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
        ("FONTSIZE", (0,0), (-1,0), 9),
        ("FONTSIZE", (0,1), (-1,-1), 7),
        ("ROWBACKGROUNDS", (0,1), (-1,-1), [colors.whitesmoke, colors.lightgrey]),
        ("GRID", (0,0), (-1,-1), 0.5, colors.black),
    ]))

    y -= (len(data) * 12)
    y = max(y, 50)  # avoid writing below the page

    table.wrapOn(c, width, height)
    table.drawOn(c, margin, y)

    # --- Footer ---
    c.setFont("Helvetica-Oblique", 8)
    c.setFillColor(colors.grey)
    c.drawString(margin, 30, f"Generated by ComplyAI | Confidential Report")

    c.save()

    return os.path.abspath(output_path)
